---
version: "2.1"
services:
  smokeping:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.internal.local`)"
      - "traefik.http.routers.smokeping.entrypoints=web"
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    networks:
      - traefik
    volumes:
      - /docker_data/smokeping/config:/config
      - /docker_data/smokeping/data:/data
    restart: unless-stopped

networks:
  traefik:
    external: true
